# Generated by Django 4.1.4 on 2022-12-08 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentenrollment',
            name='student',
        ),
        migrations.DeleteModel(
            name='SchoolClass',
        ),
        migrations.DeleteModel(
            name='StudentEnrollment',
        ),
    ]
