# Generated by Django 4.1.4 on 2022-12-08 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentenrollment',
            old_name='sclool_class',
            new_name='school_class',
        ),
    ]
